stages:
  - build

nix_build:
  tags: ["nix"]
  stage: build
  script:
  - NIXPKGS_ALLOW_INSECURE=1 nix build .#aleph2-gui .#aleph2-gz .#aleph2-viz --verbose --impure
nix_fmt:
  tags: ["nix"]
  stage: build
  script:
  - nix fmt -- -c .
