aleph2:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: base_to_frame
  joint2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: B_to_base
