#!/usr/bin/env python3

import sys

from rqt_gui.main import Main

plugin = 'aleph2_gui.aleph2_manip_controller.Aleph2ManipController'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))